# vim:set ft=tmux:
%hidden MODULE_NAME="git_branch"

set -ogq "@catppuccin_${MODULE_NAME}_icon" "

    set -ogq "@catppuccin_${MODULE_NAME}_icon" "



  set -ogqF "@catppuccin_${MODULE_NAME}_color" "#{E:@thm_mauve}"
set -ogq "@catppuccin_${MODULE_NAME}_text" " #(git -C #{pane_current_path} branch --show-current 2>/dev/null)"

source -F "#{d:current_file}/../utils/status_module.conf"
